import type { StageConfig } from './types'

export const STAGES: StageConfig[] = [
  {
    id: 1,
    runways: [{ id: 'r0', index: 0 }],
    target: 3,
    simultaneous: 1,
    speed: 1,
    spawnInterval: 5000,
    hasDepartures: false,
    hasLargeAircraft: false,
    allowedMisses: 5,
    fuelDuration: 25000,
  },
  {
    id: 2,
    runways: [{ id: 'r0', index: 0 }],
    target: 5,
    simultaneous: 2,
    speed: 1,
    spawnInterval: 4000,
    hasDepartures: true,
    hasLargeAircraft: false,
    allowedMisses: 4,
    fuelDuration: 22000,
  },
  {
    id: 3,
    runways: [
      { id: 'r0', index: 0 },
      { id: 'r1', index: 1 },
    ],
    target: 6,
    simultaneous: 3,
    speed: 1.1,
    spawnInterval: 3500,
    hasDepartures: false,
    hasLargeAircraft: false,
    allowedMisses: 4,
    fuelDuration: 20000,
  },
  {
    id: 4,
    runways: [
      { id: 'r0', index: 0 },
      { id: 'r1', index: 1 },
    ],
    target: 8,
    simultaneous: 4,
    speed: 1.2,
    spawnInterval: 3000,
    hasDepartures: true,
    hasLargeAircraft: false,
    allowedMisses: 3,
    fuelDuration: 18000,
  },
  {
    id: 5,
    runways: [
      { id: 'r0', index: 0 },
      { id: 'r1', index: 1 },
    ],
    target: 8,
    simultaneous: 4,
    speed: 1.4,
    spawnInterval: 2500,
    hasDepartures: true,
    hasLargeAircraft: true,
    allowedMisses: 3,
    fuelDuration: 15000,
  },
]
